### ISSUE TITLE
Converting Markdown to HTML Issues

### ISSUE THREAD

**Issue by james94** [hortonworks/tutorials#10]
Issues currently being resolved:
- **cannot install jekyll** with the command
     - we should include an alternative command that changes the location where jekyll will be installed. 
*That fixed my problem*.

**Comment by ZacBlanco** [comment]
@james94 Is this issue still relevant? If so can you elaborate a bit more?

**Comment by ZacBlanco** [comment]
@james94  Any more updates on this?

**Comment by ZacBlanco** [comment]
No response and lack of info. Going to close this
