### ISSUE TITLE
Build_tutorials.sh script issue

### ISSUE THREAD

**Issue by james94** [hortonworks/tutorials#11]
The hyperlinks to jump to certain parts of the page doesn't work properly. After running the **bash script** to convert all the markdown files to html, the issue below happens. 

~~~
<li><a href="#configure-and-start-solr">Configure and Start Solr</a></li>
......(more html code in between)
<h2 id="configure-and-start-solr-a-idconfigure-and-start-solra">Configure and Start Solr <a id="configure-and-start-solr"></a></h2>
~~~

href in the `<a>` tag link is correct.
Yet, the location that the link jumps to is incorrect as can be seen by the `<h2>` tag. There should be one id attribute that says: `<h2 id="configure-and-start-solr">Configure and Start Solr</h2>`
Also an anchor element does not need to be present.

Have your run into this issue?

**Comment by ZacBlanco** [comment]
@james94 I'm aware that in `<a>` tags the section links do not always work.

Currently I do not have a fix but I plan on doing some testing to figure out the best possible solution over the weekend.
