### ISSUE TITLE
Traffic Location Data URL 404s

### ISSUE THREAD

**Issue by slachterman** [hortonworks/tutorials#163]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Learning the Ropes of Apache NiFi
**HDP Version are you Running**: 2.4
**Applicable HDP Components**: NiFi

**Link to tutorial**(Hortonworks or GitHub website): https://hortonworks.com/hadoop-tutorial/learning-ropes-apache-nifi/#section_4

### Detailed Description of Issue: 
In Section 2.1, there is a link to the trafficLocs_data_for_simulator.zip file, https://hortonworks.com/assets/learning-ropes-nifi-lab-series/trafficLocs_data_for_simulator.zip

This link is currently resulting in an HTTP 404 error.

### Proposed Fix:
Fix broken URL. Looks like file can be found here: https://github.com/hortonworks/tutorials/blob/hdp/assets/learning-ropes-nifi-lab-series/trafficLocs_data_for_simulator.zip

**Comment by james94** [comment]
Thank you for your contribution. This link has been fixed on github and the tutorial on the website.
