### ISSUE TITLE
allows allows

### ISSUE THREAD

**Issue by Evorus** [hortonworks/tutorials#171]
**Tutorial Name**: 
HADOOP TUTORIAL – GETTING STARTED WITH HDP

**Link to tutorial**(Hortonworks or GitHub website):
http://hortonworks.com/hadoop-tutorial/hello-world-an-introduction-to-hadoop-hcatalog-hive-and-pig/#concepts-mapreduce-yarn

### Detailed Description of Issue:
"allows" is in twice within the following section;
**4.4 INTRODUCTION: APACHE PIG**
MapReduce **allows allows** you to specify map and reduce functions

### Proposed Fix:
remove one "allows"

**Comment by mushtaqrizvihw** [comment]
fixed
