### ISSUE TITLE
Tutorial script link missing.

### ISSUE THREAD

**Issue by mohdaliiqbal** [hortonworks/tutorials#173]
*Tutorial Name*: cross-component-lineage-using-atlas
*HDP Version*: 2.5
*Affected Components*: Atlas

https://github.com/hortonworks/tutorials/blob/hdp-2.5/tutorials/hortonworks/cross-component-lineage-using-atlas/tutorial.md

### Detailed Description of Issue:
The tutorial references scripts to download using wget. The link of the script to download is missing. 

### Proposed Fix:
Provide the link to the crosscomponent_scripts.zip

**Comment by mushtaqrizvihw** [comment]
fixed.
