### ISSUE TITLE
Incorrect command in Section 2.2.7 of Lab 2

### ISSUE THREAD

**Issue by mdeguzis** [hortonworks/tutorials#189]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Lab 2: Data Manipulation with Hive 
**HDP Version are you Running**: 2.5
**Applicable HDP Components**: Hive view

**Link to tutorial**(Hortonworks or GitHub website):

https://github.com/hortonworks/tutorials/blob/hdp-2.5/tutorials/hortonworks/hello-hdp-an-introduction-to-hadoop/hello-hdp-section-4.md

### Detailed Description of Issue:

Section 2.2.7, under "A few additional commands to explore tables", it reads

>{table_name}; - Provides a list of columns for a particular table (ie describe geolocation_stage;)

However, `geolocation;` does not work, where, `describe geolocation;` does. Per the formatting, the `{table_name};` example should reflect that, meaning `describe {table_name};` The 1st, 3rd, and 4th commands work fine. The tail end example `describe geolocation_stage;` also will not work.

Full text:

>
    show tables; - List the tables created in the database by looking up the list of tables from the metadata stored in HCatalogdescribe
    {table_name}; - Provides a list of columns for a particular table (ie describe geolocation_stage;)
    show create {table_name}; - Provides the DDL to recreate a table (ie show create table geolocation_stage;)
    describe formatted {table_name}; - Explore additional metadata about the table. For example you can verify geolocation is an ORC Table, execute the following query:

## Suggested text

>describe {table_name}; - Provides a list of columns for a particular table (ie describe geolocation;)

**Comment by mushtaqrizvihw** [comment]
Thanks for noticing, its done.
