### ISSUE TITLE
col ordering mixup in Spark Risk Factor Analysis tutorial

### ISSUE THREAD

**Issue by lestermartin** [hortonworks/tutorials#26]
There is a mixup of columns that get loaded into the finalresults table in the tutorial at http://hortonworks.com/hadoop-tutorial/hello-world-an-introduction-to-hadoop-hcatalog-hive-and-pig/#section_7.  

Check out cols 2 and 3 of the next line from the Compute Driver Risk Factor section.

`val risk_factor_spark=hiveContext.sql("select driverid, totmiles,occurance, totmiles/occurance riskfactor from joined")`

Check out cols 2 and 3 in the next line from the Create and ORC table section.

`hiveContext.sql("create table finalresults( driverid String, occurance bigint,totmiles bigint,riskfactor double) stored as orc").toDF()`

When the next line runs, we end up storing the totalmiles value into the occurance column and vice-versa.

`hiveContext.sql("load data inpath 'risk_factor_spark' into table finalresults")`

**GOOD NEWS; EASY FIX!!  Just switch the order in the first code snippet above to now read as follows.**

`val risk_factor_spark=hiveContext.sql("select driverid, occurance, totmiles, totmiles/occurance riskfactor from joined")`

**Comment by ZacBlanco** [comment]
@lestermartin can you take a look at this and confirm that the change is correct:

[https://github.com/hortonworks/tutorials/commit/f73f337a4e375e12892670bcfbe3ee4b43cdf174](https://github.com/hortonworks/tutorials/commit/f73f337a4e375e12892670bcfbe3ee4b43cdf174)

@james94 Can you review and confirm that this change is good as well and then merge the PR #31

**Comment by lestermartin** [comment]
yep @ZacBlanco , that's it.  thx!!
