### ISSUE TITLE
risk factor value interpretation misleading

### ISSUE THREAD

**Issue by lestermartin** [hortonworks/tutorials#27]
Surely not a critical item, but there is a general misrepresentation of the calculated riskfactor value in the Risk Analysis tutorials; especially in http://hortonworks.com/hadoop-tutorial/hello-world-an-introduction-to-hadoop-hcatalog-hive-and-pig/#section_9.

We are telling folks that the higher this number is, the more risk they present when in fact it is the complete opposite.  The calculation is nbrMiles / nbrBadEvents.  For example if two different driver drove 10000 miles, but Fred had 10 bad events and Barney had 1000 their riskfactors would then be 1000 and 10.

So, the tall spikes in tools like Zeppelin are actually the good drivers, not the bad ones.

Again, not a critical item, but could cause some confusion for someone really thinking about the tutorial, not just clicking through it as fast as they can.  We could either just clean up the wording on the spots that talk to this, or consider making the formula nbrBadEvents / nbrMiles.  That approach would give the worse driver Barney a riskfactor of 0.1 and the good driver, Fred, 0.001.  The actual nbrs wouldn't be all that high with this approach, but the disparity and spread will still exist.

**Comment by ZacBlanco** [comment]
@lestermartin I believe that I realized this some time ago and fixed it. However, some loss of data occurred along the way and we lost the changes. I will see if we can get this changed. From what I remember it wasn't difficult to fix.

@james94

**Comment by lestermartin** [comment]
agreed, it should be relatively easy enough to wordsmith a bit.  although... it does loose a bit of visual appeal as now we're looking at the tall peaks in tools like Zeppelin as the "bad guys" when those rare ones are really the exceptionally "safe" drivers.  ;-)  like i said, not a critical one to resolve for sure, but it should be on the list.  thx!!

**Comment by james94** [comment]
I'll fix this problem today. Thanks Lester and Zac!
