### ISSUE TITLE
Change Heading Types for Learning the Ropes Tutorial

### ISSUE THREAD

**Issue by ZacBlanco** [hortonworks/tutorials#51]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Learning the Ropes of the Hortonworks Sandbox
**HDP Version are you Running**: hdp-2.4
**Applicable HDP Components**: Sandbox

**Link to tutorial**(Hortonworks or GitHub website):http://hortonworks.com/hadoop-tutorial/learning-the-ropes-of-the-hortonworks-sandbox/

### Detailed Description of Issue:

Change headings of subsections to be be h3 or h2's instead. The h5's look smaller than the text. Makes it a bit difficult to follow at points

### Proposed Fix:

Simply change markdown lines from "#####" to "###" or "##"

@james94

**Comment by ZacBlanco** [comment]
Actually I would say just change some of the h5 to h4's instead. Maybe h3. But the h5's are definitely too small.

**Comment by james94** [comment]
Thanks zac. I will make that change once I get into the office.
