### ISSUE TITLE
Update "Hadoop Tutorial – Getting Started with HDP" Tutorial

### ISSUE THREAD

**Issue by thejimbirch** [hortonworks/tutorials#60]
**Tutorial Name**: Hadoop Tutorial – Getting Started with HDP
**HDP Version are you Running**: N/A
**Applicable HDP Components**:N/A

**Link to tutorial**(Hortonworks or GitHub website):
http://hortonworks.com/hadoop-tutorial/hello-world-an-introduction-to-hadoop-hcatalog-hive-and-pig/#section_9

### Detailed Description of Issue:
Updated content from Zoomdata

### Proposed Fix:
PR Forthcoming.

**Comment by ZacBlanco** [comment]
I see the changes made it into the tutorial - closing this now
