### ISSUE TITLE
Integrate NiFi into IoT Tutorial Series

### ISSUE THREAD

**Issue by james94** [hortonworks/tutorials#73]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Realtime Event Processing with Storm and Kafka (Tutorial Series)
**HDP Version are you Running**: 2.4
**HDF Version are you Running**: 1.2
**Applicable HDP Components**: Storm, Kafka, HBase, Hive

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/simulating-transporting-realtime-events-stream-apache-kafka/

### Detailed Description of Issue:
Currently we do not have NiFi incorporated in this tutorial series, yet it is a powerful tool to read in the data and do some processing on it. Right now the Kafka producer creates messages and publishes it to a kafka cluster. However, we can use NiFi's processor to activate a stream simulator that generates truck event data and another processor to push it onto a Kafka cluster. How will it affect storm and hbase later in the lab?  Our IoT tutorial lacks showing the community the process of integrating Hortonworks DataFlow with Hortonworks DataPlatform services (Kafka and Storm).

### Proposed Fix:
Integrate NiFi into this tutorial series to add automating the flow of data. We want to read in data, do some filtering on it while it is flowing and push it to a kafka cluster. Storm will be used to capture that data and do some processing. We will test HBase and Hive to see how our table has changed after using NiFi.

**Comment by ZacBlanco** [comment]
Hey James I actually started working on this already. I have a branch. I may not have pushed it to github yet though

**Comment by james94** [comment]
Hey Zac, 
What branch is your tutorial under?
