### ISSUE TITLE
Updates in the tutorial "Deploying Hortonworks Sandbox on Microsoft Azure"

### ISSUE THREAD

**Issue by mushtaqrizvihw** [hortonworks/tutorials#91]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Deploying Hortonworks Sandbox on Microsoft Azure
**HDP Version are you Running**: 2.4
**Applicable HDP Components**: Sandbox

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/deploying-hortonworks-sandbox-on-microsoft-azure/

### Detailed Description of Issue:
Have to add a hyperlink

### Proposed Fix:
Added a link to go to the another tutorial

**Comment by james94** [comment]
@mushtaqrizvihw 
- completed update for this tutorial
