### ISSUE TITLE
install-nifi.sh script not updating run configs

### ISSUE THREAD

**Issue by james94** [hortonworks/tutorials#93]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Real-Time Event Processing Lab Series and NiFi Streaming Lab Series
**HD Version are you Running**: HDF 1.2.0.1 and HDP 2.4
**Applicable HDP Components**: 

**Link to tutorial**(Hortonworks or GitHub website):

### Detailed Description of Issue:
install-nifi.sh does not update the run config files.

![install_nifi_error](https://cloud.githubusercontent.com/assets/11840449/15480691/bcff2ed6-20db-11e6-9dcf-a0ef376ec5f1.png)

**Link to install-nifi.sh file**:
https://github.com/hortonworks/tutorials/blob/hdp/assets/realtime-event-processing/install-nifi.sh

### Proposed Fix:
Need to fix lines after updating run configs in the source code

@ZacBlanco

**Comment by ZacBlanco** [comment]
Uh from the picture it looks like the nifi directory wasn't present.

Double check the archive structure of the compressed HDF release. Make sure that when the archive is extracted that there is a `nifi` folder. With these updated releases the name may have changed- You'll need to simply just change where you see the references to the `nifi` folder to whatever the new name of the folder is.

I'll check back once I get a copy of HDF to find the new file path.

**Comment by james94** [comment]
The latest version of HDF has the same structure of the previous release. I manually went through the steps in the script and was able to successfully install nifi. 

Thanks, I appreciate your help.

**Comment by ZacBlanco** [comment]
looks like we just need to change the command from
`cd HDF-1.2.0.1/nifi`

into

`cd HDF-1.2.0.1-1/nifi`


But because the script uses variables to create the paths you might have just typed the wrong version.

Try using the HDF version as 1.2.0.1-1 instead of just 1.2.0.1

Let me know the results.

**Comment by james94** [comment]
The script worked with that hdf version modification.
